### ISSUE TITLE
ACF 5: Sites dropdown menu has everything marked as 'selected'

### ISSUE THREAD

**Issue by paulgeisler** [jonathan-dejong/acf-sites#2]

**Comment by jonathan-dejong** [comment]
On activation?

**Comment by paulgeisler** [comment]
No, in the edit screen of a post ( custom post type in my case).
![screenshot 2014-08-25 14 29 45](https://cloud.githubusercontent.com/assets/2124038/4029689/c8092efe-2c53-11e4-92c8-1a81b24f8a8b.png)
'Garnbleiche' was saved

**Comment by jonathan-dejong** [comment]
I'll have a look as soon as I can, Will notify you when it's been fixed :)

**Comment by paulgeisler** [comment]
Thanks! ;)

**Comment by jonathan-dejong** [comment]
This has been resolved!
