### ISSUE TITLE
Does not list all network sites

### ISSUE THREAD

**Issue by filip-van-hoeckel** [jonathan-dejong/acf-sites#5]
In our installation 2 sites are skipped in the listing. Please advise, thanks.
![skipped-sites](https://cloud.githubusercontent.com/assets/1392188/9271654/f08b75b4-427b-11e5-80b2-2f4ee716b388.png)

**Comment by jonathan-dejong** [comment]
Hi @filip-van-hoeckel 

It's probably due to their "status" not being set to active. Head over to network -> sites and edit the sites missing.

**Comment by filip-van-hoeckel** [comment]
Well, they were 'active' but for some reason not 'public'. Checking the box made the site show up. Now if only I can deduce how these site were added without _any status. Thanks anyway.

**Comment by jonathan-dejong** [comment]
Right! That's the one I meant :) Hard to remember and I didn't check one of my own MU setups first.
